### PR TITLE
update changelog

### PR DESCRIPTION
**Pull request by mgeplf**

### CODE REVIEW

**Comment by arnaudon** [comment]
I'm using auto-changelog, to track all changes, if you like it you an merge this, or I'll revert

**Review by arnaudon — APPROVED** [review]

**Comment by mgeplf** [comment]
Hmm, turns out to have been a bad idea: it's an RST file, not a markdown one....

**Comment by mgeplf** [comment]
sadly no

**Comment by arnaudon** [comment]
let me fix the filetype in anohter PR

**Pull request merged**
